export interface ItemTableMapping {
  table: string;
  type: string;
  tableCode: number;
  iconFolder: string;
  iconCol: string | null;
  hasIcon: boolean;
}

export const ITEM_TABLE_MAPPINGS: ItemTableMapping[] = [
  // Armor
  {
    table: 'tbl_code_upper',
    type: 'Upper',
    tableCode: 0,
    iconFolder: 'armor',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_lower',
    type: 'Lower',
    tableCode: 1,
    iconFolder: 'armor',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_gauntlet',
    type: 'Gauntlet',
    tableCode: 2,
    iconFolder: 'armor',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_shoe',
    type: 'Shoes',
    tableCode: 3,
    iconFolder: 'armor',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_helmet',
    type: 'Helmet',
    tableCode: 4,
    iconFolder: 'armor',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_shield',
    type: 'Shield',
    tableCode: 5,
    iconFolder: 'weapon',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_weapon',
    type: 'Weapon',
    tableCode: 6,
    iconFolder: 'weapon',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_cloak',
    type: 'Cloak',
    tableCode: 7,
    iconFolder: 'eleboost',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_ring',
    type: 'Ring',
    tableCode: 8,
    iconFolder: 'eleboost',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_amulet',
    type: 'Amulet',
    tableCode: 9,
    iconFolder: 'eleboost',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_bullet',
    type: 'Bullet',
    tableCode: 10,
    iconFolder: 'ammo',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_maketool',
    type: 'Maketool',
    tableCode: 11,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_bag',
    type: 'Bag',
    tableCode: 12,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_potion',
    type: 'Potion',
    tableCode: 13,
    iconFolder: 'potion',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_bag',
    type: 'Bag',
    tableCode: 14,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_force',
    type: 'Force',
    tableCode: 15,
    iconFolder: 'force',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_battery',
    type: 'Battery',
    tableCode: 16,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_ore',
    type: 'Ore',
    tableCode: 17,
    iconFolder: 'ore',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_resource',
    type: 'Resource',
    tableCode: 18,
    iconFolder: 'resource',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_force',
    type: 'Force',
    tableCode: 19,
    iconFolder: 'force',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_booty',
    type: 'Booty',
    tableCode: 20,
    iconFolder: 'booty',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_map',
    type: 'Map',
    tableCode: 21,
    iconFolder: 'map',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_town',
    type: 'Town',
    tableCode: 22,
    iconFolder: 'map',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_battledungeon',
    type: 'Battle Dungeon',
    tableCode: 23,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_animus',
    type: 'Animus',
    tableCode: 24,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_guardtower',
    type: 'Guard Tower',
    tableCode: 25,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_trap',
    type: 'Trap',
    tableCode: 26,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_siegekit',
    type: 'Siege Kit',
    tableCode: 27,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_ticket',
    type: 'Ticket',
    tableCode: 28,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_animus',
    type: 'Animus',
    tableCode: 29,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_recovery',
    type: 'Recovery Potion',
    tableCode: 30,
    iconFolder: 'potion',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_box',
    type: 'Box',
    tableCode: 31,
    iconFolder: 'potion',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_firecracker',
    type: 'Fire Cracker',
    tableCode: 32,
    iconFolder: 'potion',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_unmannedminer',
    type: 'Unmannedminer',
    tableCode: 33,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_radar',
    type: 'Radar',
    tableCode: 34,
    iconFolder: 'booty',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_npclink',
    type: 'Npc Link',
    tableCode: 35,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  },
  {
    table: 'tbl_code_coupon',
    type: 'Coupon',
    tableCode: 36,
    iconFolder: 'default',
    iconCol: 'item_icon',
    hasIcon: true,
  }
];